{{- if .Values.deviceRegistryExample.enabled }}
#
# Copyright (c) 2019 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
#
apiVersion: v1
kind: Service
metadata:
  {{- $args := dict "dot" . "component" "service-device-registry" "name" "service-device-registry-ext" }}
  {{- include "hono.metadata" $args | nindent 2 }}
  {{- with .Values.deviceRegistryExample.svc.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
  - name: http
    port: 28080
    protocol: TCP
    targetPort: http
    {{- $httpArgs := dict "dot" . "port" 31080 }}
    {{- include "hono.nodePort" $httpArgs | nindent 4 }}
  - name: https
    port: 28443
    protocol: TCP
    targetPort: https
    {{- $httpsArgs := dict "dot" . "port" 31443 }}
    {{- include "hono.nodePort" $httpsArgs | nindent 4 }}
  {{- if .Values.adapters.externalAdaptersEnabled }}
  - name: amqps
    port: 5671
    protocol: TCP
    targetPort: amqps
  {{- end }}
  selector:
    {{- include "hono.matchLabels" $args | nindent 4 }}
  {{- include "hono.serviceType" . }}
{{- with .Values.deviceRegistryExample.svc.loadBalancerIP }}
  loadBalancerIP: {{ . | quote }}
{{- end }}
{{- end }}
