#
# Copyright (c) 2020 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
#

# profile for installing Hono
# - without monitoring infrastructure
# - with example Infinispan data grid
# - with Kafka messaging only
# - with MQTT adapter only

useLoadBalancer: false

dataGridExample:
  enabled: true

kafka:
  externalAccess:
    enabled: false
  serviceAccount:
    create: false
  rbac:
    create: false

adapters:
  amqp:
    enabled: false
  coap:
    enabled: false
  http:
    enabled: false
  mqtt:
    enabled: true
  lora:
    enabled: false
