{{- $amqpEnabled := and ( has "amqp" .Values.messagingNetworkTypes ) .Values.amqpMessagingNetworkExample.enabled -}}
{{- if $amqpEnabled }}
#
# Copyright (c) 2019 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
#
apiVersion: apps/v1
kind: Deployment
metadata:
  {{- $args := dict "dot" . "component" "amqp-messaging-network-router" "name" "dispatch-router" "componentConfig" .Values.amqpMessagingNetworkExample.dispatchRouter }}
  {{- include "hono.metadata" $args | nindent 2 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "hono.matchLabels" $args | nindent 6 }}
  template:
    metadata:
      {{- include "hono.metadata" $args | nindent 6 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- include "hono.pod.priorityClassName" $args | nindent 6 }}
      {{- include "hono.pod.affinity" $args | nindent 6 }}
      containers:
      - name: apache-qpid-dispatch-router
        image: {{ .Values.amqpMessagingNetworkExample.dispatchRouter.imageName | quote }}
        imagePullPolicy: IfNotPresent
        command:
        - /sbin/qdrouterd
        - -c
        - {{ .Values.amqpMessagingNetworkExample.dispatchRouter.configPath }}
        env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - name: amqps
          containerPort: 5671
          protocol: TCP
        {{- if .Values.amqpMessagingNetworkExample.insecurePortEnabled }}
        - name: amqp
          containerPort: 5672
          protocol: TCP
        {{- end }}
        - name: internal
          containerPort: 5673
          protocol: TCP
        {{- with .Values.amqpMessagingNetworkExample.dispatchRouter.resources }}
        resources:
          {{- . | toYaml | nindent 10 }}
        {{- end }}
        # In general, we would rather use the /healthz resource provided by qdrouterd's HTTP server.
        # However, the libwebsockets library used by older dispatch router images will try to allocate
        # memory for a lot of file descriptors and fail with an OOM during startup, effectively preventing
        # the HTTP server from starting and in turn preventing the pod to ever reach the ready state.
        # see https://github.com/eclipse-packages/packages/issues/312
        #
        # We therefore use a simple TCP socket check on the internal AMQP port for the liveness and readiness probes,
        # which is sufficient for our use case.
        {{- $probes := mergeOverwrite ( .Values.probes | deepCopy ) ( $args.componentConfig.probes | default dict | deepCopy ) }}
        {{- $deprecatedLivenessProbeInitialDelaySeconds := default .Values.livenessProbeInitialDelaySeconds $args.componentConfig.livenessProbeInitialDelaySeconds }}
        {{- $deprecatedReadinessProbeInitialDelaySeconds := default .Values.readinessProbeInitialDelaySeconds $args.componentConfig.readinessProbeInitialDelaySeconds }}
        livenessProbe:
          tcpSocket:
            port: 5673
          periodSeconds: {{ $probes.livenessProbe.periodSeconds }}
          failureThreshold: {{ $probes.livenessProbe.failureThreshold }}
          initialDelaySeconds: {{ default $probes.livenessProbe.initialDelaySeconds $deprecatedLivenessProbeInitialDelaySeconds }}
          successThreshold: {{ $probes.livenessProbe.successThreshold }}
          timeoutSeconds: {{ $probes.livenessProbe.timeoutSeconds }}
        readinessProbe:
          tcpSocket:
            port: 5673
          periodSeconds: {{ $probes.readinessProbe.periodSeconds }}
          failureThreshold: {{ $probes.readinessProbe.failureThreshold }}
          initialDelaySeconds: {{ default $probes.readinessProbe.initialDelaySeconds $deprecatedReadinessProbeInitialDelaySeconds }}
          successThreshold: {{ $probes.readinessProbe.successThreshold }}
          timeoutSeconds: {{ $probes.readinessProbe.timeoutSeconds }}
        securityContext:
          privileged: false
        volumeMounts:
        {{- include "hono.container.volumeMounts" ( dict "name" $args.name "componentConfig" $args.componentConfig ) | indent 8 }}
      volumes:
      {{- include "hono.pod.volumes" $args | indent 6 }}
{{- end }}
