{{- if .Values.amqpMessagingNetworkExample.enabled }}
#
# Copyright (c) 2019, 2020 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
#
apiVersion: v1
kind: Secret
metadata:
  {{- $args := dict "dot" . "component" "amqp-messaging-network-router" "name" "dispatch-router-conf" }}
  {{- include "hono.metadata" $args | nindent 2 }}
type: Opaque
stringData:
  "qdrouterd.json": |
    {{- tpl ( .Files.Get "config/router/qdrouterd.json" ) . | nindent 4 }}
data:
  "qdrouter-key.pem": {{ .Files.Get "example/certs/qdrouter-key.pem" | b64enc }}
  "qdrouter-cert.pem": {{ .Files.Get "example/certs/qdrouter-cert.pem" | b64enc }}
  "trusted-certs.pem": {{ .Files.Get "example/certs/trusted-certs.pem" | b64enc }}
  "broker-password" : {{ .Values.amqpMessagingNetworkExample.broker.saslPassword | b64enc }}
{{- end }}
