{{ $ref := (dict "root" . "partOf" "sso" "component" "operator" "name" "keycloak-operator" ) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-operator
  labels:
    {{- include "eclipse-iot-telemetry.labels" $ref  | nindent 4 }}

spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "eclipse-iot-telemetry.selectorLabels" $ref  | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "eclipse-iot-telemetry.labels" $ref  | nindent 8 }}
    spec:
      serviceAccountName: keycloak-operator
      containers:
        - name: keycloak-operator
          image: "quay.io/keycloak/keycloak-operator:{{ .Values.keycloak.version }}"
          imagePullPolicy: IfNotPresent
          command: [ "keycloak-operator" ]
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "keycloak-operator"
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
