#
# Copyright (c) 2020 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
#
---
{{- if ( and .Values.hono.deviceRegistryExample.enabled .Values.hono.deviceRegistryExample.data.volumeName ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default "c2e-registry-data" .Values.hono.deviceRegistryExample.extraSecretMounts.registrydata.secretName | quote }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "c2e.name" . }}
    helm.sh/chart: {{ template "c2e.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
type: Opaque
stringData:
  {{ .Values.hono.deviceRegistryExample.data.devicesFile }}: |
    {{- .Files.Get "example-device-identities.json" | nindent 4 }}
  {{ .Values.hono.deviceRegistryExample.data.credentialsFile }}: |
    {{- .Files.Get "example-credentials.json" | nindent 4 }}
  {{ .Values.hono.deviceRegistryExample.data.tenantsFile }}: |
    {{- .Files.Get "example-tenants.json" | nindent 4 }}
{{- end }}
