#
# Copyright (c) 2020 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
#
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" .Release.Name "post-install-data" | quote }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "c2e.name" . }}
    helm.sh/chart: {{ template "c2e.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
type: Opaque
stringData:
  demo-device-thing.json: |
    {{- .Files.Get "post-install/thing-definition.json" | nindent 4 }}
  hono-connection.json: |
    {{- tpl (.Files.Get "post-install/hono-connection.json") . | nindent 4 }}
  demo-device-credentials.json: |
    {{- tpl (.Files.Get "post-install/demo-device-credentials.json") . | nindent 4 }}
