# Copyright (c) 2019, 2022 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0

# consider helm install to be failed after 30 minutes
helm-extra-args: --timeout 30m
check-version-increment: true
debug: true
chart-dirs:
  - charts
  - packages
chart-repos:
  - stable=https://charts.helm.sh/stable
  - packages=https://eclipse.org/packages/charts
  - bitnami=https://charts.bitnami.com/bitnami
  - prometheus-community=https://prometheus-community.github.io/helm-charts
  - grafana=https://grafana.github.io/helm-charts
excluded-charts:
  - telemetry-e2e
  - cloud2edge
