{{- if .Values.fileStorage.azure.dynamicFileShare }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azure-file-sc
provisioner: kubernetes.io/azure-file
parameters:
  skuName: Standard_LRS
{{- end }}
