kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "hawkbit.fullname" . }}
  labels:
{{ include "hawkbit.labels" . | indent 4 }}
data:
  application.yaml: |-
{{ toYaml .Values.config.application | indent 4}}
