kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "hawkbit.fullname" . }}
  labels:
{{ include "hawkbit.labels" . | indent 4 }}
data:
  application.yaml: |-
    {{- $rabbitmqConfig := dict -}}
    {{- if .Values.rabbitmq.enabled -}}
    {{- $rabbitmqConfig = dict "spring" (dict
        "rabbitmq" (dict
          "host" (printf "%s-rabbitmq" .Release.Name)
          "username" .Values.rabbitmq.auth.username
        )
        "cloud" (dict "stream" (dict "bindings" (dict
          "default"        (dict "group" "hawkbit")
          "device-created" (dict "destination" "device-registry.device-created")
          "device-updated" (dict "destination" "device-registry.device-updated")
          "device-deleted" (dict "destination" "device-registry.device-deleted")
        )))
      ) -}}
    {{- else -}}
    {{- $rabbitmqConfig = dict "spring" (dict "autoconfigure" (dict "exclude" "org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration")) -}}
    {{- end -}}
    {{- $authConfig := dict "hawkbit" (dict "security" (dict "user" (dict (.Values.auth.username) (dict "tenant" "DEFAULT" "roles" (list "TENANT_ADMIN"))))) -}}
    {{- mergeOverwrite (deepCopy .Values.config.application) $rabbitmqConfig $authConfig | toYaml | nindent 4 }}
