{{- if .Values.gui.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hawkbit.fullname" . }}-gui
  labels:
{{ include "hawkbit.labels" . | indent 4 }}
    app.kubernetes.io/component: gui
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.gui.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "hawkbit.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: gui
{{- end }}
