{{- if .Values.ingress.enabled -}}
{{- $apiVersion := include "hawkbit.ingressAPIVersion" . -}}
{{- $fullName := include "hawkbit.fullname" . -}}
{{- $hostsHawkbitSimpleUIport  := .Values.ingress.hosts_hawkbit_simple_ui.port -}}
{{- $hostsHawkbitPort  := .Values.ingress.hosts_hawkbit.port -}}
apiVersion: {{ $apiVersion }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
{{ include "hawkbit.labels" . | indent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  {{- if eq $apiVersion "networking.k8s.io/v1" }}
  ingressClassName: {{ .Values.ingress.ingressClassName  }}
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts_hawkbit.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: {{ .paths }}
            {{- if eq $apiVersion "networking.k8s.io/v1" }}
            pathType: Prefix
            backend:
              service:
                name: {{ .service }}
                port:
                  number: {{ .port }}
            {{- else }}
            backend:
              serviceName: {{ include "hawkbit.fullname" . }}
              servicePort: {{  $hostsHawkbitPort }}
            {{- end }}
  {{- end }}
{{- end }}
