{{- if .Values.ingress.enabled -}}
{{- $apiVersion := include "hawkbit.ingressAPIVersion" . -}}
{{- $fullName := include "hawkbit.fullname" . -}}
apiVersion: {{ $apiVersion }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "hawkbit.labels" . | indent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  {{- if eq $apiVersion "networking.k8s.io/v1" }}
  ingressClassName: {{ .Values.ingress.ingressClassName  }}
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts_hawkbit }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ . }}
            {{- if eq $apiVersion "networking.k8s.io/v1" }}
            pathType: Prefix
            backend:
              service:
                name: hawkbit
                port:
                  name: http
            {{- else }}
            backend:
              serviceName: hawkbit
              servicePort: http
            {{- end }}
        {{- end }}
  {{- end }}
  {{- range .Values.ingress.hosts_hawkbit_simple_ui }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ . }}
            {{- if eq $apiVersion "networking.k8s.io/v1" }}
            pathType: Prefix
            backend:
              service:
                name: hawkbit-simple-ui-deployement
                port:
                  name: http
            {{- else }}
            backend:
              serviceName: hawkbit-simple-ui-deployement
              servicePort: http
            {{- end }}
        {{- end }}
  {{- end }}
{{- end }}
