{{- if and .Values.fileStorage.enabled ( not .Values.fileStorage.azure.staticSecret ) -}}
{{- $fullName := include "hawkbit.fullname" . -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $fullName }}-data
  labels:
{{ include "hawkbit.labels" . | indent 4 }}
  {{- with .Values.fileStorage.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.fileStorage.pvcSize }}
  {{- if .Values.fileStorage.azure.dynamicFileShare }}
  storageClassName: azure-file-sc
  {{- end }}
{{- end }}
