{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "hawkbit.fullname" . }}
  labels:
{{ include "hawkbit.labels" . | indent 4 }}
type: Opaque
data:
{{- if .Values.config.secrets }}
  hawkbit-dmf-password: {{ .Values.config.secrets.hawkbit.dmf.hono.password | b64enc | quote }}
  hawkbit-password: {{ .Values.config.secrets.spring.securinty.user.password | b64enc | quote }}
{{- else }}
  hawkbit-dmf-password: {{ .Values.auth.dmfPassword | b64enc | quote }}
  hawkbit-password: {{ .Values.auth.password | b64enc | quote }}
{{- end }}
{{- end }}
