apiVersion: v1
kind: Secret
metadata:
  name: {{ template "hawkbit.fullname" . }}
  labels:
{{ include "hawkbit.labels" . | indent 4 }}
type: Opaque
data:
  SPRING_APPLICATION_JSON: {{ .Values.config.secrets | toJson | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "hawkbit.fullname" . }}-rabbitmq-pass
  labels:
    app.kubernetes.io/name: {{ include "hawkbit.name" . }}
    helm.sh/chart: {{ include "hawkbit.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  rabbitmq-pass: {{ .Values.env.springRabbitmqPassword | b64enc | quote }}
