{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "hawkbit.fullname" . }}-user
  labels:
{{ include "hawkbit.labels" . | indent 4 }}
type: Opaque
stringData:
  application-user-credentials.yaml: |-
    hawkbit:
      security:
        user:
          {{ .Values.auth.username }}:
            password: {{ .Values.auth.password | quote }}
---
{{- end }}
{{- if and (not .Values.externalDatabase.existingSecret) (not .Values.mysql.enabled) .Values.externalDatabase.host }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "hawkbit.fullname" . }}-db
  labels:
{{ include "hawkbit.labels" . | indent 4 }}
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: {{ include "hawkbit.database.user" . | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.externalDatabase.password | quote }}
---
{{- end }}
{{- if and (not .Values.externalDatabase.existingSecret) .Values.mysql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "hawkbit.fullname" . }}-db
  labels:
{{ include "hawkbit.labels" . | indent 4 }}
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_DATASOURCE_PASSWORD: {{ .Values.mysql.auth.rootPassword | default "" | quote }}
---
{{- end }}
{{- if and .Values.rabbitmq.enabled (not .Values.rabbitmq.credentialsSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "hawkbit.fullname" . }}-rabbitmq
  labels:
{{ include "hawkbit.labels" . | indent 4 }}
type: Opaque
stringData:
  SPRING_RABBITMQ_USERNAME: {{ .Values.rabbitmq.auth.username | quote }}
  SPRING_RABBITMQ_PASSWORD: {{ .Values.rabbitmq.auth.password | quote }}
{{- end }}
