# Copyright (c) 2019 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
#
{{- if not .Values.gateway.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ditto.fullname" . }}-gateway-secret
  labels:
    app.kubernetes.io/name: {{ include "ditto.name" . }}-gateway-secret
{{ include "ditto.labels" . | indent 4 }}
type: Opaque
data:
  {{- if .Values.gateway.devopsPassword }}
  devops-password: {{ .Values.gateway.devopsPassword | b64enc | quote }}
  {{- else }}
  devops-password: {{ randAlphaNum 12 | b64enc | quote }}
  {{- end }}
  {{- if .Values.gateway.statusPassword }}
  status-password: {{ .Values.gateway.statusPassword | b64enc | quote }}
  {{- else }}
  status-password: {{ randAlphaNum 12 | b64enc | quote }}
  {{- end }}
{{- end }}
