# Copyright (c) 2019, 2020 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
#
{{- if .Values.swaggerui.enabled -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ditto.fullname" . }}-swaggerui
  labels:
    app.kubernetes.io/name: {{ include "ditto.name" . }}-swaggerui
{{ include "ditto.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.swaggerui.replicaCount }}
  strategy:
  {{- with .Values.swaggerui.updateStrategy }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ditto.name" . }}-swaggerui
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "ditto.name" . }}-swaggerui
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- with .Values.swaggerui.additionalLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- with .Values.swaggerui.additionalAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: {{ .Chart.Name }}-init
          image: "{{ .Values.swaggerui.image.repository }}:{{ .Values.swaggerui.image.tag }}"
          imagePullPolicy: {{ .Values.swaggerui.image.pullPolicy }}
          command:
            - sh
            - -ec
            - |
               mkdir -p /usr/share/nginx/html/openapi 
               curl -sL https://raw.githubusercontent.com/eclipse/ditto/{{ .Chart.AppVersion }}/documentation/src/main/resources/openapi/ditto-api-2.yml -o /usr/share/nginx/html/openapi/ditto-openapi-2.yaml               
               cp -rv /etc/nginx/. /init-config/
               cp -rv /usr/share/nginx/html/. /init-content/
               mkdir /var/lib/nginx/logs
               mkdir /var/lib/nginx/tmp
          volumeMounts:
            - name: swagger-ui-config
              mountPath: /init-config
            - name: swagger-ui-content
              mountPath: /init-content
            - name: swagger-ui-work
              mountPath: /var/lib/nginx
      containers:
        - name: {{ .Chart.Name }}-swaggerui
          image: "{{ .Values.swaggerui.image.repository }}:{{ .Values.swaggerui.image.tag }}"
          imagePullPolicy: {{ .Values.swaggerui.image.pullPolicy }}
          env:
            - name: QUERY_CONFIG_ENABLED
              value: "true"
            {{- if .Values.swaggerui.extraEnv }}
              {{- toYaml .Values.swaggerui.extraEnv | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          {{- with .Values.swaggerui.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: swagger-ui-cache
              mountPath: /var/cache/nginx
            - name: swagger-ui-work
              mountPath: /var/lib/nginx
            - name: swagger-ui-config
              mountPath: /etc/nginx
            - name: swagger-ui-content
              mountPath: /usr/share/nginx/html
            - name: swagger-ui-run
              mountPath: /run/nginx
      volumes:
        - name: swagger-ui-cache
          emptyDir: {}
        - name: swagger-ui-work
          emptyDir: {}
        - name: swagger-ui-config
          emptyDir: {}
        - name: swagger-ui-content
          emptyDir: {}
        - name: swagger-ui-run
          emptyDir: {}
{{- end }}
