# Copyright (c) 2019 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
{{- if and .Values.swaggerui.podDisruptionBudget.enabled (gt .Values.swaggerui.replicaCount 1.0) -}}
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "ditto.fullname" . }}-swaggerui
  labels:
    app.kubernetes.io/name: {{ include "ditto.name" . }}-swaggerui
{{ include "ditto.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ditto.name" . }}-swaggerui
      app.kubernetes.io/instance: {{ .Release.Name }}
  minAvailable: {{ .Values.swaggerui.podDisruptionBudget.minAvailable }}
{{- end }}
