#
# Copyright (c) 2021 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
#
apiVersion: v2
type: application
name: telemetry-e2e

version: 0.1.0
appVersion: "0.1.0"

kubeVersion: ">= 1.19.0"

description: |
  The Eclipse IoT Telemetry end-to-end package is an example on how to acquire telemetry data and process it
  in the cloud. Covering the three tiers of IoT (Sensor, Gateway, Cloud) with Eclipse IoT and other Open Source
  technologies.

keywords:
  - IoT
  - telemetry
  - end-to-end
  - digital-twin
  - kafka

home: https://eclipse.org/packages/packages/telemetry-e2e/
icon: https://eclipse.org/packages/packages/telemetry-e2e/images/telemetry-e2e-icon.svg

sources:
  - https://github.com/eclipse/packages/packages/telemetry-e2e/

maintainers:
  - name: ctron
    email: jreimann@redhat.com

dependencies:
  - name: strimzi-kafka-operator
    repository: https://strimzi.io/charts/
    version: 0.25.0
    alias: strimzi
  - name: drogue-cloud-common
    repository: https://drogue-iot.github.io/drogue-cloud-helm-charts/
    version: ^0.3.0
  - name: drogue-cloud-core
    repository: https://drogue-iot.github.io/drogue-cloud-helm-charts/
    version: ^0.3.14
    alias: drogueCloud
  - name: ditto
    repository: https://eclipse.org/packages/charts/
    version: ~2.1.2
  - name: streamsheets
    repository: https://ctron.github.io/helm-charts
    version: ^0.2.3
