{{- if .Values.adapters.mqtt.enabled }}
#
# Copyright (c) 2019, 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
#
apiVersion: v1
kind: Service
metadata:
  {{- $args := dict "dot" . "component" "adapter-mqtt" "name" "adapter-mqtt" }}
  {{- include "hono.metadata" $args | nindent 2 }}
  {{- with .Values.adapters.mqtt.svc.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
  {{- if ( eq .Values.adapters.mqtt.hono.mqtt.insecurePortEnabled true ) }}
  - name: mqtt
    port: 1883
    protocol: TCP
    targetPort: mqtt
    {{- $mqttArgs := dict "dot" . "port" 31883 }}
    {{- include "hono.nodePort" $mqttArgs | nindent 4 }}
  {{- end }}
  - name: secure-mqtt
    port: 8883
    protocol: TCP
    targetPort: secure-mqtt
    {{- $mqttsArgs := dict "dot" . "port" 30883 }}
    {{- include "hono.nodePort" $mqttsArgs | nindent 4 }}
  selector:
    {{- include "hono.matchLabels" $args | nindent 4 }}
  {{- include "hono.serviceType" . }}
{{- with .Values.adapters.mqtt.svc.loadBalancerIP }}
  loadBalancerIP: {{ . | quote }}
{{- end }}
{{- end }}
