# Copyright (c) 2020, 2022 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
---
dependencies:
  - name: mysql
    version: 6.14.10
    # referenced chart version not in main bitnami index any more, therefore using the full index (see https://github.com/bitnami/charts/issues/10833)
    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
    condition: mysql.enabled
  - name: rabbitmq
    version: 7.8.0
    # referenced chart version not in main bitnami index any more, therefore using the full index (see https://github.com/bitnami/charts/issues/10833)
    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
    condition: rabbitmq.enabled
