{{- if and .Values.useCommandRouter .Values.commandRouterService.enabled }}
{{- $args := dict "dot" . "name" "service-command-router" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- include "hono.metadata" $args | nindent 2 }}
{{- end }}
