{{- if and .Values.useCommandRouter .Values.commandRouterService.enabled }}
#
# Copyright (c) 2021 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
#
apiVersion: v1
kind: Service
metadata:
  {{- $args := dict "dot" . "component" "service-command-router" "name" "service-command-router" }}
  {{- include "hono.metadata" $args | nindent 2 }}
  {{- with .Values.commandRouterService.svc.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
  - name: amqps
    port: 5671
    protocol: TCP
    targetPort: amqps
  selector:
    {{- include "hono.matchLabels" $args | nindent 4 }}
  {{- include "hono.serviceType" . }}
{{- with .Values.commandRouterService.svc.loadBalancerIP }}
  loadBalancerIP: {{ . | quote }}
{{- end }}
{{- end }}
