{{- if .Values.jaegerBackendExample.enabled }}
#
# Copyright (c) 2021 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
#
{{- $args := dict "dot" . "component" "tracing" "name" "jaeger-all-in-one-conf" "componentConfig" .Values.jaegerBackendExample }}
apiVersion: v1
kind: Secret
metadata:
  {{- include "hono.metadata" $args | nindent 2 }}
type: Opaque
stringData:
  default-sampling-strategies.json: |
    {{- tpl ( .Files.Get "example/jaeger/default-sampling-strategies.json" ) . | nindent 4 }}
{{- end }}
