{{- if .Values.jaegerBackendExample.enabled }}
#
# Copyright (c) 2019, 2022 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
#
apiVersion: v1
kind: Service
metadata:
  {{- $args := dict "dot" . "component" "tracing" "name" "jaeger-collector" }}
  {{- include "hono.metadata" $args | nindent 2 }}
spec:
  ports:
  - name: collector-grpc
    port: 14250
    protocol: TCP
    targetPort: collector-grpc
  - name: otlp-grpc
    port: 4317
    protocol: TCP
    targetPort: otlp-grpc
  selector:
    {{- include "hono.matchLabels" $args | nindent 4 }}
  type: ClusterIP
{{- end }}
