#
# Copyright (c) 2019, 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
#
{{- $args := dict "dot" . "component" "service-auth" "name" "service-auth-conf" }}
apiVersion: v1
kind: Secret
metadata:
  {{- include "hono.metadata" $args | nindent 2 }}
type: Opaque
stringData:
  application.yml: |
    hono:
      app:
        maxInstances: {{ .Values.authServer.hono.app.maxInstances }}
      auth:
        amqp:
          {{- if not ( empty .Values.authServer.hono.auth.amqp ) }}
          {{- .Values.authServer.hono.auth.amqp | toYaml | nindent 10 }}
          {{- else }}
          bindAddress: "0.0.0.0"
          keyPath: "/opt/hono/tls/tls.key"
          certPath: "/opt/hono/tls/tls.crt"
          {{- end }}
        svc:
          {{- with .Values.authServer.hono.auth.svc }}
          {{- . | toYaml | nindent 10 }}
          {{- end }}
    {{- include "hono.quarkusConfig" $args | indent 4 }}
data:
  permissions.json: {{ .Files.Get "example/example-permissions.json" | b64enc }}
