#
# Copyright (c) 2019, 2021 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
#
{{- $args := dict "dot" . "component" "service-auth" "name" "service-auth" "componentConfig" .Values.authServer }}
apiVersion: apps/v1
kind: Deployment
metadata:
  {{- include "hono.metadata" $args | nindent 2 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "hono.matchLabels" $args | nindent 6 }}
  template:
    metadata:
      {{- include "hono.metadata" $args | nindent 6 }}
      annotations:
        {{- include "hono.monitoringAnnotations" . | nindent 8 }}
    spec:
      containers:
      - image: {{ include "hono.image" $args }}
        imagePullPolicy: IfNotPresent
        name: eclipse-hono-service-auth
        ports:
        - name: health
          containerPort: {{ .Values.healthCheckPort }}
          protocol: TCP
        - name: amqps
          containerPort: 5671
          protocol: TCP
        - name: amqp
          containerPort: 5672
          protocol: TCP
        securityContext:
          privileged: false
        env:
        - name: JDK_JAVA_OPTIONS
          value: {{ .Values.authServer.javaOptions | quote }}
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        {{- include "hono.component.springEnv" $args | indent 8 }}
        volumeMounts:
        {{- include "hono.container.secretVolumeMounts" $args | indent 8 }}
        {{- with .Values.authServer.resources }}
        resources:
          {{- . | toYaml | nindent 10 }}
        {{- end }}
        {{- include "hono.component.healthChecks" $args | indent 8 }}
      volumes:
      {{- include "hono.pod.secretVolumes" $args | indent 6 }}
