{{- if .Values.adapters.coap.enabled }}
#
# Copyright (c) 2019, 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
#
{{- $args := dict "dot" . "component" "adapter-coap" "name" "adapter-coap-conf" }}
apiVersion: v1
kind: Secret
metadata:
  {{- include "hono.metadata" $args | nindent 2 }}
type: Opaque
stringData:
  application.yml: |
    hono:
      app:
        maxInstances: {{ .Values.adapters.coap.hono.app.maxInstances }}
      coap:
        {{- if not ( empty .Values.adapters.coap.hono.coap  ) }}
        {{- .Values.adapters.coap.hono.coap | toYaml | nindent 8 }}
        {{- else }}
        insecurePortEnabled: false
        bindAddress: "0.0.0.0"
        port: 5684
        keyPath: "/opt/hono/tls/tls.key"
        certPath: "/opt/hono/tls/tls.crt"
        tenantIdleTimeout: {{ .Values.adapters.defaultTenantIdleTimeout | quote }}
        {{- end }}
      {{- include "hono.serviceClientConfig" $args | nindent 6 }}
    {{- include "hono.quarkusConfig" $args | indent 4 }}
data:
  adapter.credentials: {{ .Files.Get "example/coap-adapter.credentials" | b64enc }}
{{- end }}
