{{- if .Values.adapters.coap.enabled }}
#
# Copyright (c) 2019 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
#
apiVersion: v1
kind: Service
metadata:
  {{- $args := dict "dot" . "component" "adapter-coap-vertx" "name" "adapter-coap-vertx" }}
  {{- include "hono.metadata" $args | nindent 2 }}
  {{- with .Values.adapters.coap.svc.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  ports:
  - name: coap
    port: 5683
    protocol: UDP
    targetPort: coap
    {{- $coapArgs := dict "dot" . "port" 30683 }}
    {{- include "hono.nodePort" $coapArgs | nindent 4 }}
  - name: coaps
    port: 5684
    protocol: UDP
    targetPort: coaps
    {{- $coapsArgs := dict "dot" . "port" 30684 }}
    {{- include "hono.nodePort" $coapsArgs | nindent 4 }}
  selector:
    {{- include "hono.matchLabels" $args | nindent 4 }}
  {{- include "hono.serviceType" . }}
{{- with .Values.adapters.coap.svc.loadBalancerIP }}
  loadBalancerIP: {{ . | quote }}
{{- end }}
{{- end }}
