{{- if .Values.adapters.coap.enabled }}
#
# Copyright (c) 2019, 2020 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
#
{{- $args := dict "dot" . "component" "adapter-coap-vertx" "name" "adapter-coap-vertx-conf" }}
apiVersion: v1
kind: Secret
metadata:
  {{- include "hono.metadata" $args | nindent 2 }}
type: Opaque
stringData:
  application.yml: |
    hono:
      app:
        maxInstances: {{ .Values.adapters.coap.hono.app.maxInstances }}
      coap:
        {{- if .Values.adapters.coap.hono.coap }}
        {{- .Values.adapters.coap.hono.coap | toYaml | nindent 8 }}
        {{- else }}
        bindAddress: "0.0.0.0"
        port: 5684
        tenantIdleTimeout: {{ .Values.adapters.defaultTenantIdleTimeout | quote }}
        {{- end }}
      {{- include "hono.healthServerConfig" .Values.adapters.coap.hono.healthCheck | nindent 6 }}
      {{- include "hono.serviceClientConfig" $args | nindent 6 }}
data:
  key.pem: {{ .Files.Get "example/certs/coap-adapter-key.pem" | b64enc }}
  cert.pem: {{ .Files.Get "example/certs/coap-adapter-cert.pem" | b64enc }}
  trusted-certs.pem: {{ .Files.Get "example/certs/trusted-certs.pem" | b64enc }}
  adapter.credentials: {{ .Files.Get "example/coap-adapter.credentials" | b64enc }}
{{- end }}
