{{- if and .Values.adapters.amqp.enabled ( eq .Values.platform "openshift" ) }}
#
# Copyright (c) 2019, 2022 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
#
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  {{- $args := dict "dot" . "component" "adapter-amqp" "name" "adapter-amqp-sec" }}
  {{- include "hono.metadata" $args | nindent 2 }}
spec:
  port:
    targetPort: amqps
  tls:
    termination: passthrough
  to:
    kind: Service
    name: {{ printf "%s-adapter-amqp" ( include "hono.fullname" $args ) }}
{{- end }}
