{{- if and .Values.deviceRegistryExample.enabled ( eq .Values.deviceRegistryExample.type "file" ) }}
#
# Copyright (c) 2019, 2021 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
#
{{- $args := dict "dot" . "component" "service-device-registry" "name" "service-device-registry" "componentConfig" .Values.deviceRegistryExample.fileBasedDeviceRegistry }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  {{- include "hono.metadata" $args | nindent 2 }}
spec:
  serviceName: {{ printf "%s-headless" $args.name }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "hono.matchLabels" $args | nindent 6 }}
  template:
    metadata:
      {{- include "hono.metadata" $args | nindent 6 }}
      annotations:
        {{- include "hono.monitoringAnnotations" . | nindent 8 }}
    spec:
      containers:
      {{- include "hono.jaeger.agent" . | indent 6 }}
      - image: {{ include "hono.image" $args }}
        imagePullPolicy: IfNotPresent
        name: eclipse-hono-service-device-registry
        ports:
        - name: health
          containerPort: {{ .Values.healthCheckPort }}
          protocol: TCP
        - name: http
          containerPort: 8080
          protocol: TCP
        - name: https
          containerPort: 8443
          protocol: TCP
        - name: amqps
          containerPort: 5671
          protocol: TCP
        - name: amqp
          containerPort: 5672
          protocol: TCP
        env:
        - name: JDK_JAVA_OPTIONS
          value: {{ .Values.deviceRegistryExample.javaOptions | quote }}
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        {{- include "hono.component.springEnv" $args | indent 8 }}
        {{- include "hono.jaeger.clientConf" $args | indent 8 }}
        securityContext:
          privileged: false
        volumeMounts:
        {{- include "hono.container.secretVolumeMounts" ( dict "name" $args.name "componentConfig" .Values.deviceRegistryExample ) | indent 8 }}
        - name: "registry"
          mountPath: "/var/lib/hono/device-registry"
        {{- with .Values.deviceRegistryExample.resources }}
        resources:
          {{- . | toYaml | nindent 10 }}
        {{- end }}
        {{- include "hono.component.healthChecks" $args | indent 8 }}
      volumes:
      {{- include "hono.pod.secretVolumes" ( dict "dot" $args.dot "name" $args.name "componentConfig" .Values.deviceRegistryExample ) | indent 6 }}
      - name: "registry"
        persistentVolumeClaim:
          claimName: {{ printf "%s-%s" .Release.Name $args.name | quote }}
{{- end }}
