#
# Copyright (c) 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
#
{{- $args := dict "dot" . "name" "adapter" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  {{- include "hono.metadata" $args | nindent 2 }}
roleRef:
  kind: Role
  name: {{ printf "%s-%s" ( include "hono.fullname" . ) $args.name | quote }}
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ printf "%s-%s" ( include "hono.fullname" . ) $args.name | quote }}
    namespace: {{ .Release.Namespace }}
