{{ $ref := (dict "root" . "partOf" "deployment" "component" "post-install" "name" "post-install" ) }}
kind: Secret
apiVersion: v1
metadata:
  name: post-install-data
  labels:
    {{- include "eclipse-iot-telemetry.labels" $ref  | nindent 4 }}
type: Opaque
data:
  {{ $currentScope := . }}
  {{- range $path, $_ := .Files.Glob "post-install/*" }}
  {{ base $path }}: {{ tpl ( $.Files.Get $path ) $currentScope | b64enc | quote }}
  {{- end }}
